// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonShoppingCartPlus: typeof import('~icons/carbon/shopping-cart-plus')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    Cart: typeof import('./components/Cart.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    EmojioneLeafFlutteringInWind: typeof import('~icons/emojione/leaf-fluttering-in-wind')['default']
    Feature: typeof import('./components/Feature.vue')['default']
    FlatColorIconsVideoCall: typeof import('~icons/flat-color-icons/video-call')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    NotoPottedPlant: typeof import('~icons/noto/potted-plant')['default']
    ProductCard: typeof import('./components/productCard.vue')['default']
    README: typeof import('./components/README.md')['default']
    Splide: typeof import('./components/Splide.vue')['default']
    Store: typeof import('./components/Store.vue')['default']
    Thumb: typeof import('./components/Thumb.vue')['default']
  }
}

export { }
